server:
  port: 3344
spring:
  application:
    name: cloud-config-server #注册进Eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kaimugao/springcloud-config.git #git@github.com:kaimugao/springcloud-config.git # #GitHub上面的git仓库名字
          ### 搜索目录
          search-paths:
            - springcloud-config
          ### 读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
